# HTC Submit File
# This is a submit file for soft-masking genomes using funannotate mask

# Name the batch job
batch_name = "mask" 

Requirements = (Target.HasCHTCStaging == true)

# Provide HTCondor with the name of the Docker container
container_image = docker://xonq/funannotate_mask:1.8.1
universe = container

arguments = "$(SPECIES)"

executable = funannotate_mask.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

log = logs/job_mask.log
error = logs/job_mask_$(SPECIES).err
output = logs/job_mask_$(SPECIES).out

request_cpus = 6
request_memory = 4GB
request_disk = 4GB

retry_request_memory_increase = RequestMemory * N
retry_request_memory_max = 128GB

queue SPECIES from mask_parameters.txt
